Controllers/FirstModController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication6.Managers.FirstMod;

namespace WebApplication6.Controllers
{
    public class FirstModController : Controller
    {
        private readonly IFirstModManager _manager;

        public FirstModController(IFirstModManager manager)
        {
            _manager = manager;
        }


        [HttpGet]
        public async Task<ViewResult> ShowFirstMod()
        {
            var entity = await _manager.GetAll();
            return View(entity);
        }

        [HttpGet]
        public async Task<ViewResult> UpdateFirstMod(Guid id)
        {
            var entity = await _manager.GetById(id);
            return View(entity);
        }

        public ViewResult AddFirstMod()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Add(CreateOrUpdateFirstMod request)
        {
            await _manager.AddFirstMod(request);
            return RedirectToAction(nameof(ShowFirstMod));
        }

        [HttpPost]
        public async Task<ActionResult> Update(Guid GroupId, CreateOrUpdateFirstMod request)
        {
            await _manager.UpdateFirstMod(GroupId, request);
            return RedirectToAction(nameof(ShowFirstMod));
        }

        [HttpGet]
        public async Task<ActionResult> DeleteFirstMod(Guid id)
        {
            await _manager.DeleteFirstMod(id);
            return RedirectToAction(nameof(ShowFirstMod));
        }
    }
}

Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication6.Managers.Groups;

namespace WebApplication6.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupManager _manager;

        public GroupController(IGroupManager manager)
        {
            _manager = manager;
        }

        public ViewResult HomePage()
        {
            return View();
        }

        [HttpGet]
        public async Task<ViewResult> ShowGroups()
        {
            var entity = await _manager.GetAll();

            return View(entity);
        }

        [HttpGet]
        public async Task<ViewResult> UpdateGroup(Guid id)
        {
            var entity = await _manager.GetById(id);
            return View(entity);
        }

        public ViewResult AddGroup()
        {
            return View();
        }


      [HttpPost]
      public async Task<ActionResult> Add(CreateOrUpdateGroupRequest request)
      {
            await _manager.AddGroup(request);
            return RedirectToAction(nameof(ShowGroups));
      }

      [HttpPost]
      public async Task<ActionResult> Update(Guid GroupId, CreateOrUpdateGroupRequest request)
        {
            await _manager.UpdateGroup(GroupId, request);
           // await _manager.DeleteGroup(GroupId);
            return RedirectToAction(nameof(ShowGroups));
        }

        [HttpGet]
        public async Task<ActionResult> DeleteGroup(Guid id)
        {
            await _manager.DeleteGroup(id);
            return RedirectToAction(nameof(ShowGroups));
        }

    }
}

Controllers/SecondModController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication6.Managers.SecondMod;

namespace WebApplication6.Controllers
{
    public class SecondModController : Controller
    {
        private readonly ISecondModManager _manager;

        public SecondModController(ISecondModManager manager)
        {
            _manager = manager;
        }


        [HttpGet]
        public async Task<ViewResult> ShowSecondMod()
        {
            var entity = await _manager.GetAll();
            return View(entity);
        }

        [HttpGet]
        public async Task<ViewResult> UpdateSecondMod(Guid id)
        {
            var entity = await _manager.GetById(id);
            return View(entity);
        }

        public ViewResult AddSecondMod()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Add(CreateOrUpdateSecondMod request)
        {
            await _manager.AddSecondMod(request);
            return RedirectToAction(nameof(ShowSecondMod));
        }

        [HttpPost]
        public async Task<ActionResult> Update(Guid GroupId, CreateOrUpdateSecondMod request)
        {
            await _manager.UpdateSecondMod(GroupId, request);
            return RedirectToAction(nameof(ShowSecondMod));
        }

        [HttpGet]
        public async Task<ActionResult> DeleteSecondMod(Guid id)
        {
            await _manager.DeleteSecondMod(id);
            return RedirectToAction(nameof(ShowSecondMod));
        }
    }
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication6.Managers.numbers;

namespace WebApplication6.Controllers
{
    public class StudentController : Controller
    {
        private readonly Number_sys _student;

        public StudentController(Number_sys student)
        {
            _student = student;
        }


        [HttpGet]
        public async Task<ViewResult> ShowStudent()
        {
            var entity = await _student.GetAll();

            return View(entity);
        }

        [HttpGet]
        public async Task<ViewResult> UpdateStudents(Guid id)
        {
            var entity = await _student.GetById(id);
            return View(entity);
        }

        public ViewResult AddNumbers()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Add(CreateDrUpdateNumber request)
        {
            await _student.AddNumbers(request);
            return RedirectToAction(nameof(ShowStudent));
        }

        [HttpPost]
        public async Task<ActionResult> Update(Guid GroupId, CreateDrUpdateNumber request)
        {
           await _student.UpdateStudents(GroupId, request);
          
            return RedirectToAction(nameof(ShowStudent));
        }

        public async Task<ActionResult> DeleteStudent(Guid id)
        {
            await _student.DeleteStudents(id);
            return RedirectToAction(nameof(ShowStudent));
        }
    }
}

Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication6.Managers.Subjects;

namespace WebApplication6.Controllers
{
    public class SubjectController : Controller
    {
      
        private readonly ISubjectManager _manager;

        public SubjectController(ISubjectManager manager)
        {
            _manager = manager;
        }


        [HttpGet]
        public async Task<ViewResult> ShowSubj()
        {
            var entity = await _manager.GetAll();
            return View(entity);
        }

        [HttpGet]
        public async Task<ViewResult> UpdateSubj(Guid id)
        {
            var entity = await _manager.GetById(id);
            return View(entity);
        }

        public ViewResult AddSubj()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Add(CreateOrUpdateSubjRequest request)
        {
            await _manager.AddSubj(request);
            return RedirectToAction(nameof(ShowSubj));
        }

        [HttpPost]
        public async Task<ActionResult> Update(Guid GroupId, CreateOrUpdateSubjRequest request)
        {
            await _manager.UpdateSubj(GroupId, request);
            return RedirectToAction(nameof(ShowSubj));
        }

        [HttpGet]
        public async Task<ActionResult> DeleteSubj(Guid id)
        {
            await _manager.DeleteSubj(id);
            return RedirectToAction(nameof(ShowSubj));
        }
    }
    

}

Views/FirstMod/AddFirstMod.cshtml
@model WebApplication6.Managers.FirstMod.CreateOrUpdateFirstMod

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddFirstMod</title>
</head>
<body>
    @using (Html.BeginForm("Add", "FirstMod", FormMethod.Post))
    {
        <label>Оценка: </label>
        <input id="FirstMd" type="text" name="FirstMd" /><br /><br />

        <input type="submit" value="Добавить новую оценку" />
    }

    <div>
        @Html.ActionLink("Вернуться на страницу вывода модулей", "ShowFirstMod", "FirstMod")
    </div>
</body>
</html>

Views/FirstMod/ShowFirstMod.cshtml
@model IEnumerable<WebApplication6.Storage.Entity.FirstM>

    @{
        Layout = null;
    }

    <!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>ShowFirstMod</title>
    </head>
    <body>
        <div>
            <h1>Первый модуль</h1>
            @foreach (var item in Model)
            {
                <label>ID: </label>@item.id<br />
                <label>Оценка: </label>@item.FirstMd<br />
                <a href="/FirstMod/UpdateFirstMod/@item.id">Редактировать модуль</a><br /><br />// контроллер -> метод -> передаем Idшник
            }


            @using (Html.BeginForm("AddFirstMod", "FirstMod"))
            {
                <div>
                    <input type="submit" value="Добавить новый модуль" />
                </div>
            }

            <p></p>

            @using (Html.BeginForm("HomePage", "Group"))
            {
                <div>
                    <input type="submit" value="Вернуться" />
                </div>
            }


        </div>
    </body>
</html>

Views/FirstMod/UpdateFirstMod.cshtml
@model WebApplication6.Storage.Entity.FirstM

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateFirstMod</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Update", "FirstMod", FormMethod.Post)) // все элементы будт переданы скрытым образом в результирующий набор нашей формы
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />

            <label>Оценка: </label>
            <input id="FirstMd" type="text" name="FirstMd" value="@Model.FirstMd" /><br /><br />
            <input type="submit" value="Редактировать модуль" />


        }

        @using (Html.BeginForm("DeleteFirstMod", "FirstMod", FormMethod.Get))
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />
            <input type="submit" value="удалить модуль" />
        }


        <div>
            @Html.ActionLink("Вернуться на страницу ввода модулей", "ShowFirstMod", "FirstMod")
        </div>

    </div>
</body>
</html>

Views/Group/AddGroup.cshtml
@model WebApplication6.Managers.Groups.CreateOrUpdateGroupRequest

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddGroup</title>
</head>
<body>
    @using (Html.BeginForm("Add", "Group", FormMethod.Post))
    {
        <label>Номер группы: </label>
        <input id="Name" type="text" name="Name" /><br /><br />

        <label>Направление: </label>
        <input id="DepartmentNumber" type="text" name="DepartmentNumber" /><br /><br />

        <input type="submit" value="Добавить новую группу" />
    }

    <div>
        @Html.ActionLink("Вернуться на страницу вывода групп", "ShowGroups", "Group")
    </div>
</body>
</html>

Views/Group/HomePage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Данные</title>
</head>
<body>
    <div>
        <h1>Деканат</h1>

        @using (Html.BeginForm("ShowGroups", "Group", FormMethod.Get))
        {
            <div>
                <input type="submit" value="Группы" />
            </div>
        }

        <p></p>
        @using (Html.BeginForm("ShowStudent", "Student", FormMethod.Get))
        {
            <div>
                <input type="submit" value="Студенты" />
            </div>
        }

        <p></p>
        @using (Html.BeginForm("ShowSubj", "Subject", FormMethod.Get))
        {
            <div>
                <input type="submit" value="Предметы" />
            </div>
        }

        <p></p>
        @using (Html.BeginForm("ShowFirstMod", "FirstMod", FormMethod.Get))
        {
            <div>
                <input type="submit" value="Первый модуль" />
            </div>
        }

        <p></p>
        @using (Html.BeginForm("ShowSecondMod", "SecondMod", FormMethod.Get))
        {
            <div>
                <input type="submit" value="Второй модуль" />
            </div>
        }

    </div>
</body>
</html>

Views/Group/ShowGroups.cshtml
@model IEnumerable<WebApplication6.Storage.Entity.Group>

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowGroups</title>
</head>
<body>
    <div>
        <h1>Группы</h1>
        @foreach (var item in Model)
        {
            <label>ID: </label>@item.id<br />
            <label>Номер группы: </label>@item.Name<br />
            <label>Направление: </label>@item.DepartmentNumber<br />
            <a href="/Group/UpdateGroup/@item.id">Редактировать группу</a><br /><br />// контроллер -> метод -> передаем Idшник
        }


        @using (Html.BeginForm("AddGroup", "Group"))
        {
            <div>
                <input type="submit" value="Добавить новую группу" />
            </div>
        }

        <p></p>

        @using (Html.BeginForm("HomePage", "Group"))
        {
            <div>
                <input type="submit" value="Вернуться" />
            </div>
        }


    </div>
</body>
</html>

Views/Group/UpdateGroup.cshtml
@model WebApplication6.Storage.Entity.Group

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateGroup</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Update", "Group", FormMethod.Post)) // все элементы будт переданы скрытым образом в результирующий набор нашей формы
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />

            <label>Номер группы: </label>
            <input id="Name" type="text" name="Name" value="@Model.Name" /><br /><br />

            <label>Направление: </label>
            <input id="DepartmentNumber" type="text" name="DepartmentNumber" value="@Model.DepartmentNumber" /><br /><br />

            <input type="submit" value="Редактировать группу" />


        }

        <p></p>
        @using (Html.BeginForm("DeleteGroup", "Group", FormMethod.Get))
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />
            <input type="submit" value="удалить группу" />
        }


        <div>
            @Html.ActionLink("Вернуться на страницу вывода групп", "ShowGroups", "Group")
        </div>

    </div>
</body>
</html>

Views/SecondMod/AddSecondMod.cshtml
@model WebApplication6.Managers.SecondMod.CreateOrUpdateSecondMod

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddSecondMod</title>
</head>
<body>
    @using (Html.BeginForm("Add", "SecondMod", FormMethod.Post))
    {
        <label>Оценка: </label>
        <input id="SecondMd" type="text" name="SecondMd" /><br /><br />
        <input type="submit" value="Добавить новую оценку" />
    }

    <div>
        @Html.ActionLink("Вернуться на страницу вывода модулей", "ShowSecondMod", "SecondMod")
    </div>
</body>
</html>

Views/SecondMod/ShowSecondMod.cshtml
@model IEnumerable<WebApplication6.Storage.Entity.SecondM>

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowSecondMod</title>
</head>
<body>
    <div>
        <h1>Второй модуль модуль</h1>
        @foreach (var item in Model)
        {
            <label>ID: </label>@item.id<br />
            <label>Оценка: </label>@item.SecondMd<br />
            <a href="/SecondMod/UpdateSecondMod/@item.id">Редактировать модуль</a><br /><br />// контроллер -> метод -> передаем Idшник
        }


        @using (Html.BeginForm("AddSecondMod", "SecondMod"))
        {
            <div>
                <input type="submit" value="Добавить новый модуль" />
            </div>
        }

        <p></p>

        @using (Html.BeginForm("HomePage", "Group"))
        {
            <div>
                <input type="submit" value="Вернуться" />
            </div>
        }


    </div>
</body>
</html>

Views/SecondMod/UpdateSecondMod.cshtml
@model WebApplication6.Storage.Entity.SecondM

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateSecondMod</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Update", "SecondMod", FormMethod.Post)) // все элементы будт переданы скрытым образом в результирующий набор нашей формы
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />

            <label>Оценка: </label>
            <input id="SecondMd" type="text" name="SecondMd" value="@Model.SecondMd" /><br /><br />
            <input type="submit" value="Редактировать модуль" />


        }

        @using (Html.BeginForm("DeleteSecondMod", "SecondMod", FormMethod.Get))
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />
            <input type="submit" value="удалить модуль" />
        }


        <div>
            @Html.ActionLink("Вернуться на страницу ввода Модулей", "ShowSecondMod", "SecondMod")
        </div>

    </div>
</body>
</html>

Views/Student/AddNumbers.cshtml
@model WebApplication6.Storage.Entity.cal_c
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddStudent</title>
</head>
<body>
    @using (Html.BeginForm("Add", "Student", FormMethod.Post))
    {
        <label>Имя: </label>
        <input id="FirstNumber" type="text" name="FirstNumber" for="FirstNumber" /><br /><br />

        <label>Фамилия: </label>
        <input id="SecondNumber" type="text" name="SecondNumber" for="SecondNumber" /><br /><br />

        <label>Староста: </label>
        <input id="GroupLeader" type="text" name="GroupLeader" for="GroupLeader" /><br /><br />

        <label>ID Группы: </label>
        <input id="GroupID" type="text" name="GroupID" for="GroupID" /><br /><br />

        <label>ID Первого модуля: </label>
        <input id="FirstModID" type="text" name="FirstModID" for="FirstModID" /><br /><br />

        <label>ID Второго модуля: </label>
        <input id="SecondModID" type="text" name="SecondModID" for="SecondModID" /><br /><br />

        <label>ID Предмета: </label>
        <input id="SubjID" type="text" name="SubjID" for="SubjID" /><br /><br />


        <input type="submit" value="Добавить нового студента" />
    }

    <div>
        @Html.ActionLink("Вернуться на страницу вывода студентов", "ShowStudent", "Student")
    </div>
</body>
</html>

Views/Student/ShowStudent.cshtml
@model IEnumerable<WebApplication6.Storage.Entity.cal_c>

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowGroups</title>
</head>
<body>
    <div>
        <h1>Студенты</h1>
        @foreach (var item in Model)
        {
            <label>ID: </label>@item.id<br />
            <label>Имя: </label>@item.FirstNumber<br />
            <label>Фамилия: </label>@item.SecondNumber<br />
            <label>Группа: </label>@item.GroupID<br />
            <label>Предмет: </label>@item.SubjID<br />
            <label>Первый модуль: </label>@item.FirstModID<br />
            <label>Второй модуль: </label>@item.SecondModID<br />
            <label>Староста: </label>@item.GroupLeader<br />
            <a href="/Student/UpdateStudents/@item.id">Редактировать студента</a><br /><br />// контроллер -> метод -> передаем Idшник
        }


        @using (Html.BeginForm("AddNumbers", "Student"))
        {
            <div>
                <input type="submit" value="Добавить нового студента" />
            </div>
        }

        <p></p>

        @using (Html.BeginForm("HomePage", "Group"))
        {
            <div>
                <input type="submit" value="Вернуться" />
            </div>
        }


    </div>
</body>
</html>

Views/Student/UpdateStudents.cshtml
@model WebApplication6.Storage.Entity.cal_c

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateStudent</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Update", "Student", FormMethod.Post)) // все элементы будт переданы скрытым образом в результирующий набор нашей формы
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />

            <label>Имя: </label>
            <input id="FirstNumber" type="text" name="FirstNumber" value="@Model.FirstNumber" /><br /><br />

            <label>Фамилия: </label>
            <input id="SecondNumber" type="text" name="SecondNumber" value="@Model.SecondNumber" /><br /><br />

            <label>Староста: </label>
            <input id="GroupLeader" type="text" name="GroupLeader" value="@Model.GroupLeader" /><br /><br />

            <label>ID Группы: </label>
            <input id="GroupID" type="text" name="GroupID" value="@Model.GroupID" /><br /><br />

            <label>ID Первого модуля: </label>
            <input id="FirstModID" type="text" name="FirstModID" value="@Model.FirstModID" /><br /><br />

            <label>ID Второго модуля: </label>
            <input id="SecondModID" type="text" name="SecondModID" value="@Model.SecondModID" /><br /><br />


            <label>ID Предмета: </label>
            <input id="SubjID" type="text" name="SubjID" value="@Model.SubjID" /><br /><br />

            <input type="submit" value="Редактировать студента" />


        }


        @using (Html.BeginForm("DeleteStudent", "Student", FormMethod.Get))
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />
            <input type="submit" value="удалить студента" />
        }



        <div>
            @Html.ActionLink("Вернуться на страницу вывода студентов", "ShowStudent", "Student")
        </div>

    </div>
</body>
</html>

Views/Subject/AddSubj.cshtml
@model WebApplication6.Managers.Subjects.CreateOrUpdateSubjRequest

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddSubj</title>
</head>
<body>
    @using (Html.BeginForm("Add", "Subject", FormMethod.Post))
    {
        <label>Название предмета: </label>
        <input id="Name_of_Sub" type="text" name="Name_of_Sub" /><br /><br />

        <input type="submit" value="Добавить новый предмет" />
    }

    <div>
        @Html.ActionLink("Вернуться на страницу вывода предметов", "ShowSubj", "Subject")
    </div>
</body>
</html>

Views/Subject/ShowSubj.cshtml
@model IEnumerable<WebApplication6.Storage.Entity.Subject>

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowGroups</title>
</head>
<body>
    <div>
        <h1>Предметы</h1>
        @foreach (var item in Model)
        {
            <label>ID: </label>@item.id<br />
            <label>Имя: </label>@item.Name_of_Sub<br />
            <a href="/Subject/UpdateSubj/@item.id">Редактировать предмет</a><br /><br />// контроллер -> метод -> передаем Idшник
        }


        @using (Html.BeginForm("AddSubj", "Subject"))
        {
            <div>
                <input type="submit" value="Добавить новый предмет" />
            </div>
        }

        <p></p>

        @using (Html.BeginForm("HomePage", "Group"))
        {
            <div>
                <input type="submit" value="Вернуться" />
            </div>
        }


    </div>
</body>
</html>

Views/Subject/UpdateSubj.cshtml
@model WebApplication6.Storage.Entity.Subject

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateSubject</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Update", "Subject", FormMethod.Post)) // все элементы будт переданы скрытым образом в результирующий набор нашей формы
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />

            <label>Название предмета: </label>
            <input id="Name_of_Sub" type="text" name="Name_of_Sub" value="@Model.Name_of_Sub" /><br /><br />
            <input type="submit" value="Редактировать предмет" />


        }

        @using (Html.BeginForm("DeleteSubj", "Subject", FormMethod.Get))
        {
            <input id="id" name="id" type="hidden" value="@Model.id" />
            <input type="submit" value="удалить предмет" />
        }


        <div>
            @Html.ActionLink("Вернуться на страницу вывода предметов", "ShowSubj", "Subject")
        </div>

    </div>
</body>
</html>